using System.Threading.Tasks;

namespace OnvifStandard.Device;

public interface IDeviceClient : IOnvifSoapClient
{
    Task<GetServicesResponse>                        GetServices(bool includeCapability);
    Task<GetDeviceInformationResponse>               GetDeviceInformation();
    Task<GetServiceCapabilitiesResponse>             GetServiceCapabilities();
    Task<GetSystemDateAndTimeResponse>               GetSystemDateAndTime();
    Task<GetSystemLogResponse>                       GetSystemLog(SystemLogType logType);
    Task<GetSystemSupportInformationResponse>        GetSystemSupportInformation();
    Task<GetScopesResponse>                          GetScopes();
    Task<GetDiscoveryModeResponse>                   GetDiscoveryMode();
    Task<GetRemoteDiscoveryModeResponse>             GetRemoteDiscoveryMode();
    Task<GetWsdlUrlResponse>                         GetWsdlUrl();
    Task<GetEndpointReferenceResponse>               GetEndpointReference();
    Task<GetHostnameResponse>                        GetHostname();
    Task<GetPasswordComplexityOptionsResponse>       GetPasswordComplexityOptions();
    Task<GetPasswordComplexityConfigurationResponse> GetPasswordComplexityConfiguration();
    Task<GetPasswordHistoryConfigurationResponse>    GetPasswordHistoryConfiguration();
    Task<GetAuthFailureWarningOptionsResponse>       GetAuthFailureWarningOptions();
    Task<GetAuthFailureWarningConfigurationResponse> GetAuthFailureWarningConfiguration();
    Task<GetSystemBackupResponse>                    GetSystemBackup();
    Task<GetDPAddressesResponse>                     GetDPAddresses();
    Task<GetUserRolesResponse>                       GetUserRoles(string userRole = null);
    Task<GetUsersResponse>                           GetUsers();
    Task<GetDNSResponse>                             GetDNS();
    Task<GetNTPResponse>                             GetNTP();
    Task<GetDynamicDNSResponse>                      GetDynamicDNS();
    Task<GetNetworkProtocolsResponse>                GetNetworkProtocols();
    Task<GetNetworkDefaultGatewayResponse>           GetNetworkDefaultGateway();
    Task<GetZeroConfigurationResponse>               GetZeroConfiguration();
    Task<GetIPAddressFilterResponse>                 GetIPAddressFilter();
    Task<GetRemoteUserResponse>                      GetRemoteUser();
    Task<GetNetworkInterfacesResponse>               GetNetworkInterfaces();
    Task<GetAccessPolicyResponse>                    GetAccessPolicy();
    Task<GetRelayOutputsResponse>                    GetRelayOutputs();
    Task<GetDot11CapabilitiesResponse>               GetDot11Capabilities();
    Task<GetDot11StatusResponse>                     GetDot11Status(string interfaceToken);
    Task<GetSystemUrisResponse>                      GetSystemUris();
    Task<GetStorageConfigurationsResponse>           GetStorageConfigurations();
    Task<GetStorageConfigurationResponse>            GetStorageConfiguration(string token);
    Task<GetGeoLocationResponse>                     GetGeoLocation();
    Task<GetCertificatesResponse>                    GetCertificates();
    Task<GetCertificatesStatusResponse>              GetCertificatesStatus();
    Task<GetPkcs10RequestResponse>                   GetPkcs10Request(string certificateId, string subject = null, BinaryData attributes = null);
    Task<GetClientCertificateModeResponse>           GetClientCertificateMode();
    Task<GetCACertificatesResponse>                  GetCACertificates();
    Task<GetCertificateInformationResponse>          GetCertificateInformation(string certificateId);
    Task<GetDot1XConfigurationResponse>              GetDot1XConfiguration(string     dot1XConfigurationToken);
    Task<GetDot1XConfigurationsResponse>             GetDot1XConfigurations();
    Task<GetCapabilitiesResponse>                    GetCapabilities(CapabilityCategory[]                                         categories);
    Task<AddIPAddressFilterResponse>                 AddIPAddressFilter(AddIPAddressFilterRequest                                 addIPAddressFilterRequest);
    Task<AddScopesResponse>                          AddScopes(AddScopesRequest                                                   addScopesRequest);
    Task<CreateCertificateResponse>                  CreateCertificate(CreateCertificateRequest                                   createCertificateRequest);
    Task<CreateDot1XConfigurationResponse>           CreateDot1XConfiguration(CreateDot1XConfigurationRequest                     createDot1XConfigurationRequest);
    Task<CreateStorageConfigurationResponse>         CreateStorageConfiguration(CreateStorageConfigurationRequest                 createStorageConfigurationRequest);
    Task<CreateUsersResponse>                        CreateUsers(CreateUsersRequest                                               createUsersRequest);
    Task<DeleteCertificatesResponse>                 DeleteCertificates(DeleteCertificatesRequest                                 deleteCertificatesRequest);
    Task<DeleteDot1XConfigurationResponse>           DeleteDot1XConfiguration(DeleteDot1XConfigurationRequest                     deleteDot1XConfigurationRequest);
    Task<DeleteGeoLocationResponse>                  DeleteGeoLocation(DeleteGeoLocationRequest                                   deleteGeoLocationRequest);
    Task<DeleteStorageConfigurationResponse>         DeleteStorageConfiguration(DeleteStorageConfigurationRequest                 deleteStorageConfigurationRequest);
    Task<DeleteUserRoleResponse>                     DeleteUserRole(DeleteUserRoleRequest                                         deleteUserRoleRequest);
    Task<DeleteUsersResponse>                        DeleteUsers(DeleteUsersRequest                                               deleteUsersRequest);
    Task<LoadCACertificatesResponse>                 LoadCACertificates(LoadCACertificatesRequest                                 loadCACertificatesRequest);
    Task<LoadCertificatesResponse>                   LoadCertificates(LoadCertificatesRequest                                     loadCertificatesRequest);
    Task<LoadCertificateWithPrivateKeyResponse>      LoadCertificateWithPrivateKey(LoadCertificateWithPrivateKeyRequest           loadCertificateWithPrivateKeyRequest);
    Task<RemoveIPAddressFilterResponse>              RemoveIPAddressFilter(RemoveIPAddressFilterRequest                           removeIPAddressFilterRequest);
    Task<RemoveScopesResponse>                       RemoveScopes(RemoveScopesRequest                                             removeScopesRequest);
    Task<RestoreSystemResponse>                      RestoreSystem(RestoreSystemRequest                                           restoreSystemRequest);
    Task<ScanAvailableDot11NetworksResponse>         ScanAvailableDot11Networks(ScanAvailableDot11NetworksRequest                 scanAvailableDot11NetworksRequest);
    Task<SendAuxiliaryCommandResponse>               SendAuxiliaryCommand(SendAuxiliaryCommandRequest                             sendAuxiliaryCommandRequest);
    Task<SetAccessPolicyResponse>                    SetAccessPolicy(SetAccessPolicyRequest                                       setAccessPolicyRequest);
    Task<SetAuthFailureWarningConfigurationResponse> SetAuthFailureWarningConfiguration(SetAuthFailureWarningConfigurationRequest setAuthFailureWarningConfigurationRequest);
    Task<SetCertificatesStatusResponse>              SetCertificatesStatus(SetCertificatesStatusRequest                           setCertificatesStatusRequest);
    Task<SetClientCertificateModeResponse>           SetClientCertificateMode(SetClientCertificateModeRequest                     setClientCertificateModeRequest);
    Task<SetDiscoveryModeResponse>                   SetDiscoveryMode(SetDiscoveryModeRequest                                     setDiscoveryModeRequest);
    Task<SetDNSResponse>                             SetDNS(SetDNSRequest                                                         setDNSRequest);
    Task<SetDot1XConfigurationResponse>              SetDot1XConfiguration(SetDot1XConfigurationRequest                           setDot1XConfigurationRequest);
    Task<SetDPAddressesResponse>                     SetDPAddresses(SetDPAddressesRequest                                         setDPAddressesRequest);
    Task<SetDynamicDNSResponse>                      SetDynamicDNS(SetDynamicDNSRequest                                           setDynamicDNSRequest);
    Task<SetGeoLocationResponse>                     SetGeoLocation(SetGeoLocationRequest                                         setGeoLocationRequest);
    Task<SetHashingAlgorithmResponse>                SetHashingAlgorithm(SetHashingAlgorithmRequest                               setHashingAlgorithmRequest);
    Task<SetHostnameResponse>                        SetHostname(SetHostnameRequest                                               setHostnameRequest);
    Task<SetHostnameFromDHCPResponse>                SetHostnameFromDHCP(SetHostnameFromDHCPRequest                               setHostnameFromDHCPRequest);
    Task<SetIPAddressFilterResponse>                 SetIPAddressFilter(SetIPAddressFilterRequest                                 setIPAddressFilterRequest);
    Task<SetNetworkDefaultGatewayResponse>           SetNetworkDefaultGateway(SetNetworkDefaultGatewayRequest                     setNetworkDefaultGatewayRequest);
    Task<SetNetworkInterfacesResponse>               SetNetworkInterfaces(SetNetworkInterfacesRequest                             setNetworkInterfacesRequest);
    Task<SetNetworkProtocolsResponse>                SetNetworkProtocols(SetNetworkProtocolsRequest                               setNetworkProtocolsRequest);
    Task<SetNTPResponse>                             SetNTP(SetNTPRequest                                                         setNTPRequest);
    Task<SetPasswordComplexityConfigurationResponse> SetPasswordComplexityConfiguration(SetPasswordComplexityConfigurationRequest setPasswordComplexityConfigurationRequest);
    Task<SetPasswordHistoryConfigurationResponse>    SetPasswordHistoryConfiguration(SetPasswordHistoryConfigurationRequest       setPasswordHistoryConfigurationRequest);
    Task<SetRelayOutputSettingsResponse>             SetRelayOutputSettings(SetRelayOutputSettingsRequest                         setRelayOutputSettingsRequest);
    Task<SetRelayOutputStateResponse>                SetRelayOutputState(SetRelayOutputStateRequest                               setRelayOutputStateRequest);
    Task<SetRemoteDiscoveryModeResponse>             SetRemoteDiscoveryMode(SetRemoteDiscoveryModeRequest                         setRemoteDiscoveryModeRequest);
    Task<SetRemoteUserResponse>                      SetRemoteUser(SetRemoteUserRequest                                           setRemoteUserRequest);
    Task<SetScopesResponse>                          SetScopes(SetScopesRequest                                                   setScopesRequest);
    Task<SetStorageConfigurationResponse>            SetStorageConfiguration(SetStorageConfigurationRequest                       setStorageConfigurationRequest);
    Task<SetSystemDateAndTimeResponse>               SetSystemDateAndTime(SetSystemDateAndTimeRequest                             setSystemDateAndTimeRequest);
    Task<SetSystemFactoryDefaultResponse>            SetSystemFactoryDefault(SetSystemFactoryDefaultRequest                       setSystemFactoryDefaultRequest);
    Task<SetUserResponse>                            SetUser(SetUserRequest                                                       setUserRequest);
    Task<SetUserRoleResponse>                        SetUserRole(SetUserRoleRequest                                               setUserRoleRequest);
    Task<SetZeroConfigurationResponse>               SetZeroConfiguration(SetZeroConfigurationRequest                             setZeroConfigurationRequest);
    Task<StartFirmwareUpgradeResponse>               StartFirmwareUpgrade(StartFirmwareUpgradeRequest                             startFirmwareUpgradeRequest);
    Task<StartSystemRestoreResponse>                 StartSystemRestore(StartSystemRestoreRequest                                 startSystemRestoreRequest);
    Task<SystemRebootResponse>                       SystemReboot(SystemRebootRequest                                             systemRebootRequest);
    Task<UpgradeFirmwareResponse>                    UpgradeFirmware(UpgradeFirmwareRequest                                       upgradeFirmwareRequest);
    Task<UpgradeSystemFirmwareResponse>              UpgradeSystemFirmware(UpgradeSystemFirmwareRequest                           upgradeSystemFirmwareRequest);
}