using System.Threading.Tasks;

namespace OnvifStandard.Media;

public interface IMediaClient : IOnvifSoapClient
{
    Task<GetServiceCapabilitiesResponse>                     GetServiceCapabilities();
    Task<GetVideoSourcesResponse>                            GetVideoSources();
    Task<GetAudioSourcesResponse>                            GetAudioSources();
    Task<GetAudioOutputsResponse>                            GetAudioOutputs();
    Task<CreateProfileResponse>                              CreateProfile(string name, string token = null);
    Task<GetProfileResponse>                                 GetProfile(string    profileToken);
    Task<GetProfilesResponse>                                GetProfiles();
    Task<DeleteProfileResponse>                              DeleteProfile(string                     profileToken);
    Task<AddVideoEncoderConfigurationResponse>               AddVideoEncoderConfiguration(string      profileToken, string configurationToken);
    Task<RemoveVideoEncoderConfigurationResponse>            RemoveVideoEncoderConfiguration(string   profileToken);
    Task<AddVideoSourceConfigurationResponse>                AddVideoSourceConfiguration(string       profileToken, string configurationToken);
    Task<RemoveVideoSourceConfigurationResponse>             RemoveVideoSourceConfiguration(string    profileToken);
    Task<AddAudioEncoderConfigurationResponse>               AddAudioEncoderConfiguration(string      profileToken, string configurationToken);
    Task<RemoveAudioEncoderConfigurationResponse>            RemoveAudioEncoderConfiguration(string   profileToken);
    Task<AddAudioSourceConfigurationResponse>                AddAudioSourceConfiguration(string       profileToken, string configurationToken);
    Task<RemoveAudioSourceConfigurationResponse>             RemoveAudioSourceConfiguration(string    profileToken);
    Task<AddPTZConfigurationResponse>                        AddPTZConfiguration(string               profileToken, string configurationToken);
    Task<RemovePTZConfigurationResponse>                     RemovePTZConfiguration(string            profileToken);
    Task<AddVideoAnalyticsConfigurationResponse>             AddVideoAnalyticsConfiguration(string    profileToken, string configurationToken);
    Task<RemoveVideoAnalyticsConfigurationResponse>          RemoveVideoAnalyticsConfiguration(string profileToken);
    Task<AddMetadataConfigurationResponse>                   AddMetadataConfiguration(string          profileToken, string configurationToken);
    Task<RemoveMetadataConfigurationResponse>                RemoveMetadataConfiguration(string       profileToken);
    Task<AddAudioOutputConfigurationResponse>                AddAudioOutputConfiguration(string       profileToken, string configurationToken);
    Task<RemoveAudioOutputConfigurationResponse>             RemoveAudioOutputConfiguration(string    profileToken);
    Task<AddAudioDecoderConfigurationResponse>               AddAudioDecoderConfiguration(string      profileToken, string configurationToken);
    Task<RemoveAudioDecoderConfigurationResponse>            RemoveAudioDecoderConfiguration(string   profileToken);
    Task<GetVideoSourceConfigurationsResponse>               GetVideoSourceConfigurations();
    Task<GetVideoEncoderConfigurationsResponse>              GetVideoEncoderConfigurations();
    Task<GetAudioSourceConfigurationsResponse>               GetAudioSourceConfigurations();
    Task<GetAudioEncoderConfigurationsResponse>              GetAudioEncoderConfigurations();
    Task<GetVideoAnalyticsConfigurationsResponse>            GetVideoAnalyticsConfigurations();
    Task<GetMetadataConfigurationsResponse>                  GetMetadataConfigurations();
    Task<GetAudioOutputConfigurationsResponse>               GetAudioOutputConfigurations();
    Task<GetAudioDecoderConfigurationsResponse>              GetAudioDecoderConfigurations();
    Task<GetVideoSourceConfigurationResponse>                GetVideoSourceConfiguration(string                         configurationToken);
    Task<GetVideoEncoderConfigurationResponse>               GetVideoEncoderConfiguration(string                        configurationToken);
    Task<GetAudioSourceConfigurationResponse>                GetAudioSourceConfiguration(string                         configurationToken);
    Task<GetAudioEncoderConfigurationResponse>               GetAudioEncoderConfiguration(string                        configurationToken);
    Task<GetVideoAnalyticsConfigurationResponse>             GetVideoAnalyticsConfiguration(string                      configurationToken);
    Task<GetMetadataConfigurationResponse>                   GetMetadataConfiguration(string                            configurationToken);
    Task<GetAudioOutputConfigurationResponse>                GetAudioOutputConfiguration(string                         configurationToken);
    Task<GetAudioDecoderConfigurationResponse>               GetAudioDecoderConfiguration(string                        configurationToken);
    Task<GetCompatibleVideoEncoderConfigurationsResponse>    GetCompatibleVideoEncoderConfigurations(string             profileToken);
    Task<GetCompatibleVideoSourceConfigurationsResponse>     GetCompatibleVideoSourceConfigurations(string              profileToken);
    Task<GetCompatibleAudioEncoderConfigurationsResponse>    GetCompatibleAudioEncoderConfigurations(string             profileToken);
    Task<GetCompatibleAudioSourceConfigurationsResponse>     GetCompatibleAudioSourceConfigurations(string              profileToken);
    Task<GetCompatibleVideoAnalyticsConfigurationsResponse>  GetCompatibleVideoAnalyticsConfigurations(string           profileToken);
    Task<GetCompatibleMetadataConfigurationsResponse>        GetCompatibleMetadataConfigurations(string                 profileToken);
    Task<GetCompatibleAudioOutputConfigurationsResponse>     GetCompatibleAudioOutputConfigurations(string              profileToken);
    Task<GetCompatibleAudioDecoderConfigurationsResponse>    GetCompatibleAudioDecoderConfigurations(string             profileToken);
    Task<SetVideoSourceConfigurationResponse>                SetVideoSourceConfiguration(VideoSourceConfiguration       configuration,             bool?  forcePersistence = null);
    Task<SetVideoEncoderConfigurationResponse>               SetVideoEncoderConfiguration(VideoEncoderConfiguration     configuration,             bool?  forcePersistence = null);
    Task<SetAudioSourceConfigurationResponse>                SetAudioSourceConfiguration(AudioSourceConfiguration       configuration,             bool?  forcePersistence = null);
    Task<SetAudioEncoderConfigurationResponse>               SetAudioEncoderConfiguration(AudioEncoderConfiguration     configuration,             bool?  forcePersistence = null);
    Task<SetVideoAnalyticsConfigurationResponse>             SetVideoAnalyticsConfiguration(VideoAnalyticsConfiguration configuration,             bool?  forcePersistence = null);
    Task<SetMetadataConfigurationResponse>                   SetMetadataConfiguration(MetadataConfiguration             configuration,             bool?  forcePersistence = null);
    Task<SetAudioOutputConfigurationResponse>                SetAudioOutputConfiguration(AudioOutputConfiguration       configuration,             bool?  forcePersistence = null);
    Task<SetAudioDecoderConfigurationResponse>               SetAudioDecoderConfiguration(AudioDecoderConfiguration     configuration,             bool?  forcePersistence = null);
    Task<GetVideoSourceConfigurationOptionsResponse>         GetVideoSourceConfigurationOptions(string                  configurationToken = null, string profileToken     = null);
    Task<GetVideoEncoderConfigurationOptionsResponse>        GetVideoEncoderConfigurationOptions(string                 configurationToken = null, string profileToken     = null);
    Task<GetAudioSourceConfigurationOptionsResponse>         GetAudioSourceConfigurationOptions(string                  configurationToken = null, string profileToken     = null);
    Task<GetAudioEncoderConfigurationOptionsResponse>        GetAudioEncoderConfigurationOptions(string                 configurationToken = null, string profileToken     = null);
    Task<GetMetadataConfigurationOptionsResponse>            GetMetadataConfigurationOptions(string                     configurationToken = null, string profileToken     = null);
    Task<GetAudioOutputConfigurationOptionsResponse>         GetAudioOutputConfigurationOptions(string                  configurationToken = null, string profileToken     = null);
    Task<GetAudioDecoderConfigurationOptionsResponse>        GetAudioDecoderConfigurationOptions(string                 configurationToken = null, string profileToken     = null);
    Task<GetGuaranteedNumberOfVideoEncoderInstancesResponse> GetGuaranteedNumberOfVideoEncoderInstances(string          configurationToken);
    Task<GetStreamUriResponse>                               GetStreamUri(StreamSetup                                   streamSetup, string profileToken);
    Task<StartMulticastStreamingResponse>                    StartMulticastStreaming(string                             profileToken);
    Task<StopMulticastStreamingResponse>                     StopMulticastStreaming(string                              profileToken);
    Task<SetSynchronizationPointResponse>                    SetSynchronizationPoint(string                             profileToken);
    Task<GetSnapshotUriResponse>                             GetSnapshotUri(string                                      profileToken);
    Task<GetVideoSourceModesResponse>                        GetVideoSourceModes(string                                 videoSourceToken);
    Task<SetVideoSourceModeResponse>                         SetVideoSourceMode(string                                  videoSourceToken, string videoSourceModeToken);
    Task<GetOSDsResponse>                                    GetOSDs(string                                             videoSourceConfigurationToken = null);
    Task<GetOSDResponse>                                     GetOSD(string                                              osdToken);
    Task<GetOSDOptionsResponse>                              GetOSDOptions(string                                       videoSourceConfigurationToken = null);
    Task<SetOSDResponse>                                     SetOSD(OSDConfiguration                                    osd);
    Task<CreateOSDResponse>                                  CreateOSD(OSDConfiguration                                 osd);
    Task<DeleteOSDResponse>                                  DeleteOSD(string                                           osdToken);
}